// deno-lint-ignore-file no-explicit-any
//
// rosterSync — nightly ClassLink OneRoster ingest.
//
// Invoked by pg_cron via pg_net (see the commented schedule in migration
// 0049) and manually for testing. Like processTimeTriggers, it carries no
// JWT from pg_net, so deploy with --no-verify-jwt and gate on the internal
// token instead:
//
//   supabase functions deploy rosterSync --no-verify-jwt
//
// Auth: X-Quest-Internal-Token header must match QUEST_INTERNAL_TOKEN.
//
// Required secrets:
//   CLASSLINK_ROSTER_API_KEY — partner-level bearer token for the OAuth2
//     proxy (generated by a Partner Portal Administrator under Settings).
//   QUEST_INTERNAL_TOKEN     — already set for the cron/email functions.
// Optional:
//   CLASSLINK_PROXY_BASE     — override the proxy origin (tests/sandboxes).
//
// Request body (all optional):
//   { "mode": "full" | "delta",      default: delta if the tenant has synced
//                                    before, full otherwise
//     "tenantId": "<sync tenant id>" limit the run to one tenant
//     "fixtures": "full" | "delta1"  serve canned fixture responses instead
//                                    of calling ClassLink (MOCK MODE — lets
//                                    the entire pipeline run end-to-end with
//                                    no ClassLink access; DB writes are real)
//   }
//
// Flow per run:
//   1. GET /applications on the proxy → upsert classlink_sync_tenants (every
//      district that granted access gets a row; new rows default enabled).
//   2. For each enabled tenant: syncTenant() — orgs → academicSessions →
//      users → classes → enrollments (see engine.ts).
//   3. Every tenant run writes a classlink_sync_runs row with per-entity
//      counts; one tenant failing does not block the others.

import { json } from '../_shared/cors.ts';
import { adminClient } from '../_shared/client.ts';
import { OneRosterClient, FetchLike } from '../_shared/oneroster.ts';
import { syncTenant, TenantRow } from './engine.ts';
import { FIXTURES } from './fixturesData.ts';

const INTERNAL_TOKEN = Deno.env.get('QUEST_INTERNAL_TOKEN') || '';
const API_KEY = Deno.env.get('CLASSLINK_ROSTER_API_KEY') || '';

// ---------------------------------------------------------------------------
// Fixture mode: serve canned collections for data requests and discovery.
// Keeps the full engine + DB path hot without ClassLink connectivity — used
// for acceptance testing and certification dry-runs. Fixtures live in
// fixtures/*.json in the repo (read from disk when present, e.g. local dev)
// with an inlined copy (fixturesData.ts) for deployed bundles.
// ---------------------------------------------------------------------------
function fixtureFetch(scenario: string): FetchLike {
  const dir = new URL(`./fixtures/`, import.meta.url);
  return async (url: string) => {
    const path = new URL(url).pathname;
    const isApplications = path.endsWith('/applications');
    const entity = isApplications ? 'applications' : (path.split('/').filter(Boolean).pop() ?? '');
    let body: any = null;
    try {
      const file = isApplications
        ? new URL('applications.json', dir)
        : new URL(`${scenario}/${entity}.json`, dir);
      body = JSON.parse(await Deno.readTextFile(file));
    } catch {
      body = isApplications
        ? FIXTURES.applications
        : (FIXTURES as any)[scenario]?.[entity] ?? null;
    }
    if (!body) body = { [entity || 'items']: [] };
    // Fixtures hold the full collection; emulate offset/limit pagination.
    const u = new URL(url);
    const limit = Number(u.searchParams.get('limit') ?? 500);
    const offset = Number(u.searchParams.get('offset') ?? 0);
    const out = JSON.parse(JSON.stringify(body));
    const key = Object.keys(out).find((k) => Array.isArray(out[k]));
    if (key) out[key] = out[key].slice(offset, offset + limit);
    return new Response(JSON.stringify(out), {
      status: 200, headers: { 'Content-Type': 'application/json' },
    });
  };
}

// Tolerant reader for the proxy's /applications entries — field naming in
// the response is not guaranteed, so probe the common spellings.
function readApp(app: any): { appId: string; tenantId: string | null; name: string | null } | null {
  const appId = app?.oneroster_applications_id ?? app?.oneroster_application_id ??
    app?.applicationId ?? app?.app_id ?? app?.id ?? null;
  if (!appId) return null;
  return {
    appId: String(appId),
    tenantId: app?.tenant_id != null ? String(app.tenant_id)
      : app?.tenantId != null ? String(app.tenantId) : null,
    name: app?.tenant_name ?? app?.tenantName ?? app?.name ?? null,
  };
}

// Config fallback: Vault (see migration vault_internal_config). The internal
// token is generated inside Postgres and read by pg_cron when it builds the
// request header; we accept it here alongside the env secret so the two
// never have to be hand-synchronized. get_vault_secret() is a
// security-definer function executable by service_role only.
const vaultCache: Record<string, string | null> = {};
async function vaultSecret(admin: any, name: string): Promise<string | null> {
  if (name in vaultCache) return vaultCache[name];
  const { data, error } = await admin.rpc('get_vault_secret', { secret_name: name });
  vaultCache[name] = error ? null : (data ?? null);
  return vaultCache[name];
}

Deno.serve(async (req) => {
  const admin = adminClient();
  const presented = req.headers.get('X-Quest-Internal-Token') ?? '';
  const vaultToken = await vaultSecret(admin, 'quest_internal_token');
  const authorized = presented.length > 0 &&
    ((INTERNAL_TOKEN && presented === INTERNAL_TOKEN) ||
      (vaultToken && presented === vaultToken));
  if (!authorized) {
    return json({ error: 'Unauthorized' }, 401);
  }

  let body: any = {};
  try { body = await req.json(); } catch { /* empty body from pg_net is fine */ }
  const fixtures = typeof body.fixtures === 'string' ? body.fixtures : null;

  const apiKey = API_KEY || (await vaultSecret(admin, 'classlink_roster_api_key')) || '';
  if (!apiKey && !fixtures) {
    return json({ error: 'CLASSLINK_ROSTER_API_KEY not configured' }, 500);
  }

  const client = new OneRosterClient({
    apiKey: fixtures ? 'fixture' : apiKey,
    fetchImpl: fixtures ? fixtureFetch(fixtures) : undefined,
  });

  const summary: any = { tenants: [], errors: 0 };

  try {
    // ---- 1. discovery: upsert a sync-tenant row per granted application --
    const apps = (await client.listApplications()).map(readApp).filter(Boolean) as
      NonNullable<ReturnType<typeof readApp>>[];
    for (const app of apps) {
      const existing = await admin.from('classlink_sync_tenants')
        .select('id').eq('oneroster_application_id', app.appId).limit(1);
      if (existing.error) throw new Error(existing.error.message);
      if (!existing.data?.length) {
        const ins = await admin.from('classlink_sync_tenants').insert({
          oneroster_application_id: app.appId,
          classlink_tenant_id: app.tenantId,
          name: app.name,
        });
        if (ins.error) throw new Error(ins.error.message);
        console.log(`[rosterSync] discovered new tenant application ${app.appId}`);
      }
    }

    // ---- 2. run each enabled tenant --------------------------------------
    let q = admin.from('classlink_sync_tenants').select('*').eq('enabled', true);
    if (typeof body.tenantId === 'string' && body.tenantId) q = q.eq('id', body.tenantId);
    // Fixture runs only ever touch the fixture tenant — never real districts.
    if (fixtures) q = q.eq('oneroster_application_id', 'APPFIX1');
    const { data: tenants, error: tErr } = await q;
    if (tErr) throw new Error(tErr.message);

    for (const tenant of (tenants ?? []) as (TenantRow & Record<string, any>)[]) {
      const mode: 'full' | 'delta' = body.mode === 'full' ? 'full'
        : body.mode === 'delta' ? 'delta'
        : tenant.last_full_sync_at ? 'delta' : 'full';

      const { data: run, error: runErr } = await admin.from('classlink_sync_runs')
        .insert({ tenant_id: tenant.id, mode }).select('id').single();
      if (runErr) throw new Error(runErr.message);

      try {
        const counts = await syncTenant({ admin, client }, tenant, mode);
        await admin.from('classlink_sync_runs').update({
          finished_at: new Date().toISOString(), ok: true, counts,
        }).eq('id', run.id);
        await admin.from('classlink_sync_tenants').update(
          mode === 'full'
            ? { last_full_sync_at: new Date().toISOString(), last_delta_sync_at: new Date().toISOString() }
            : { last_delta_sync_at: new Date().toISOString() },
        ).eq('id', tenant.id);
        summary.tenants.push({ tenant: tenant.id, mode, ok: true, counts });
      } catch (e) {
        summary.errors++;
        const msg = (e as Error).message ?? String(e);
        console.error(`[rosterSync] tenant ${tenant.id} failed: ${msg}`);
        await admin.from('classlink_sync_runs').update({
          finished_at: new Date().toISOString(), ok: false, error: msg.slice(0, 2000),
        }).eq('id', run.id);
        summary.tenants.push({ tenant: tenant.id, mode, ok: false, error: msg });
      }
    }

    summary.requests = client.requestCount;
    return json(summary, summary.errors ? 207 : 200);
  } catch (e) {
    console.error('[rosterSync] fatal:', e);
    return json({ error: (e as Error).message ?? 'sync failed' }, 500);
  }
});
